name: Run CI checks

on: pull_request

jobs:
  run_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"
      - name: Lint
        run: make lint

  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"
      - name: Test
        run: make test

  test_load:
    runs-on: ubuntu-latest
    env:
      SERVER: "http://localhost:8888/v1"
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"
      - name: Run local server
        run: |
          docker run --detach -p 8888:8888 \
            --env KINTO_INI=config/testing.ini \
            mozilla/remote-settings
      - name: Create collection
        run: |
          curl -X PUT http://localhost:8888/v1/buckets/main-workspace/collections/fxrelay-allowlist
      - name: Run job
        run: make start
