name: Run CI checks

on: pull_request

jobs:
  run_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check workflow files
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
        shell: bash
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"
      - name: Lint
        run: make lint

  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"
      - name: Test
        run: make test

  test_load:
    runs-on: ubuntu-latest
    env:
      SERVER: "http://localhost:8888/v1"
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"
      - name: Build ingestion job container
        run:
          docker build -t cronjob:test .
      - name: Run local Remote Settings server
        run: |
          docker run --detach \
            --network=host \
            --env KINTO_INI=config/testing.ini \
            mozilla/remote-settings
      - name: Create collection
        run: |
          curl -X PUT "${SERVER}/buckets/main-workspace/collections/fxrelay-allowlist"

      - name: Run job from container
        run: |
          docker run -e SERVER="${SERVER}" \
            --network=host \
            cronjob:test

      - name: Run job from source
        run: make start
